---
- name: install necessary packages
  yum: name={{ item }} state=present
  with_items:
    - httpd

- name: create user group service
  group: name=service

- name: create user httpd
  user: name=httpd group=service

