---
## main.yml

- name: cassandra_version check
  fail: msg="ERROR - required variable 'cassandra_version' missing."
  when: cassandra_version is not defined

- include: install_cassandra.yml
- include: install_cassandra_config.yml
