---
## run_cassandra_cql_commands.yml

- name: copy custom scripts first
  copy: src="{{ item }}"  dest="{{ cassandra_home }}/temp/{{ item | basename }}"
  with_fileglob: "{{ cassandra_cust_cql_scripts_dir }}/*"


- name: run custom scripts
  shell: bash -c "{{ cassandra_home }}/bin/cqlsh -u {{ cassandra_cust_cql_user }} -p {{ cassandra_cust_cql_pwd }} localhost -f {{ cassandra_home }}/temp/{{ item | basename }}"
  with_fileglob: "{{ cassandra_cust_cql_scripts_dir }}/*"
