- name: yum clean
  shell: yum clean all
  when: yum_cleaned is not defined

- name: set yum clean flag
  set_fact: 
    yum_cleaned: true

- include: packages_supervisor.yml
  when: skip_supervisord is undefined or skip_supervisord != True
