cassandra_home: /usr/local/cassandra
cassandra_logs: /usr/local/cassandra/logs
cassandra_data: /usr/local/cassandra/data
cassandra_user: cassandra
cassandra_group: cassandra
cassandra_cust_cql_user: cassandra
cassandra_cust_cql_pwd: cassandra


cassandra_cluster_name: Test Cluster
cassandra_num_tokens: 256
cassandra_authenticator: AllowAllAuthenticator
cassandra_authorizer: AllowAllAuthorizer
cassandra_role_manager: CassandraRoleManager
cassandra_partitioner: org.apache.cassandra.dht.Murmur3Partitioner
cassandra_disk_failure_policy: stop
cassandra_commit_failure_policy: stop
cassandra_listen_interface: eth0
cassandra_start_native_transport: true
cassandra_native_transport_port: 9042
cassandra_start_rpc: false
cassandra_rpc_interface: eth0
cassandra_rpc_port: 9160
