---

- name: create user group service
  group: name=service

- name: create user rpmrepo
  user: name=rpmrepo group=service

- name: create repository directory
  file: path={{ item }} state=directory group=service owner=rpmrepo
  with_items: repodirs

- name: init repository directory
  shell: createrepo {{ item }}
  sudo_user: rpmrepo
  with_items: repodirs

- name: copy update script
  template: src="../files/update_rpm_repository.sh" dest="/usr/local/bin/update_rpm_repository.sh" mode="0755"

- name: generate repo conf
  script: ../files/saas-common-repo.sh {{ repodir_root }}

