---
- name: install necessary packages
  yum: name={{ item }} state=present
  with_items:
    - httpd

- name: create user group service
  group: name=service

- name: create user httpd
  user: name=httpd group=service

- name: copy default httpd conf
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: "../files/httpd.conf", dest: "/etc/httpd/conf/httpd.conf"}
    - { src: "../files/00-0-defaultload.conf", dest: "/etc/httpd/conf.d/00-0-defaultload.conf" }
    - { src: "../files/00-0-processConfig.conf", dest: "/etc/httpd/conf.d/00-0-processConfig.conf" }
    - { src: "../files/00-zz-icon.conf", dest: "/etc/httpd/conf.d/00-zz-icon.conf" }
    - { src: "../files/01-module-mime.conf", dest: "/etc/httpd/conf.d/01-module-mime.conf" }
    - { src: "../files/01-module-dirmodule.conf", dest: "/etc/httpd/conf.d/01-module-dirmodule.conf" }
    - { src: "../files/02-default-directory.conf", dest: "/etc/httpd/conf.d/02-default-directory.conf" }

- name: Check if http port is allowed
  shell: iptables -L | grep -q "Allow http"
  register: check_allow_http
  ignore_errors: yes
  changed_when: no
  always_run: yes

- name: Allow port
  command: >
    iptables -A INPUT -p tcp -m tcp --dport {{ http_port }} -m state --state New -m comment --comment "Allow http port {{ http_port }}" -j ACCEPT
  when: check_allow_http.rc != 0
  notify:
    - Save iptables and Restart

- name: start httpd service
  service: name=httpd state=restarted

