---
- name: put mq config files
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
  with_items:
    - { src: "../files/rabbitmq-env.conf", dest: "/etc/rabbitmq/rabbitmq-env.conf", mode: "0644" }
    - { src: "../files/rabbitmq.config", dest: "/etc/rabbitmq/rabbitmq.conf", mode: "0644" }
    - { src: "../files/erlang.cookie", dest: "/var/lib/rabbitmq/.erlang.cookie", mode: "0600" }
