- include: packages.yml
- include: create-rpm-repo.yml
- include: push-httpd-conf.yml

- include: download-default-rpms.yml
  tags: updaterepo

- include: build_fpm.yml
  tags: [ updaterepo, add_new_fpms ]
  when: fpm_rpm_repository_root is defined and fpm_python_list is defined
