
- name: install erlang
  shell: rpm --import http://packages.erlang-solutions.com/rpm/erlang_solutions.asc

- name: put erlang repo file
  copy: src=erlang.repo dest=/etc/yum.repos.d/erlang.repo

- name: install packages
  yum: name={{ item }} state=present
  with_items:
    - createrepo
    - python
    - libselinux-python
    - rpm-build
    - python-devel
    - python-pip
    - libxml2
    - libxml2-devel
    - python-setuptools
    - zlib-devel
    - wget
    - openssl-devel
    - pcre
    - pcre-devel
    - gcc
    - make
    - autoconf
    - automake
